language: python

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj18 }
    - { python: 3.6, env: TOXENV=py36-dj18 }
    - { python: 2.7, env: TOXENV=py27-dj18-grp }
    - { python: 2.7, env: TOXENV=py27-dj19 }
    - { python: 3.6, env: TOXENV=py36-dj19 }
    - { python: 2.7, env: TOXENV=py27-dj19-grp }
    - { python: 2.7, env: TOXENV=py27-dj110 }
    - { python: 3.6, env: TOXENV=py36-dj110 }
    - { python: 2.7, env: TOXENV=py27-dj110-grp }
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 3.6, env: TOXENV=py36-dj111 }
    - { python: 3.6, env: TOXENV=py36-dj20 }
  allow_failures:
    - env: TOXENV=py27-dj111
    - env: TOXENV=py36-dj111
    - env: TOXENV=py36-dj20

install:
  - pip install tox 

script:
  - travis_retry travis_retry travis_retry tox -- --failfast

sudo: false
