name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]
        django-version: ["2.2", "3.1", "3.2"]
        grappelli: ["0", "1"]
        include:
          - grappelli: "1"
            name-suffix: " with grappelli"

    runs-on: ubuntu-latest
    name: Django ${{ matrix.django-version }}${{ matrix.name-suffix }} (Python ${{ matrix.python-version }})

    env:
      DJANGO: ${{ matrix.django-version }}
      GRAPPELLI: ${{ matrix.grappelli }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@v1.0.5

    - name: Install tox
      run: |
       python -m pip install tox tox-gh-actions

    - name: Run tests
      run: |
        tox -- -v2 --selenium=chrome-headless || \
        tox -- -v2 --selenium=chrome-headless || \
        tox -- -v2 --selenium=chrome-headless
